name: Build Docker Container
on:
  push:
    branches:
      - main
      - master
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Determine Docker Tag
        id: vars
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "0.0.0")
          IFS='.' read -r MAJOR MINOR PATCH <<<"$TAG"
          PATCH=$((PATCH + 1))
          echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: natha2023/backend-craftedby:${{ env.VERSION }}
